require("config.keys.misc").keys()
require("config.keys.telescope").keys()
require("config.keys.neorg").keys()
-- require("config.keys.neoscroll").keys()
require("config.keys.neotree").keys()
require("config.keys.gitsigns").keys()
require("config.keys.diffview").keys()
require("config.keys.truezen").keys()
