-- require "config.plugins.neorg"
require "config.plugins.completion"
require "config.plugins.fidget"
require "config.plugins.lualine"
-- require "config.plugins.barbar"
require "config.plugins.tabby"
require "config.plugins.neotree"
require "config.plugins.oil"
require "config.plugins.whichkey"
require "config.plugins.indentblankline"
require "config.plugins.telescope"
require "config.plugins.actionspreview"
require "config.plugins.mini"
require "config.plugins.autopairs"
require "config.plugins.comment"
require "config.plugins.gitsigns"
require "config.plugins.diffview"
require "config.plugins.truezen"
require "config.plugins.render-markdown"
require "config.plugins.markdown-preview"
require "config.plugins.vimtex"
require "config.plugins.sonokai"
