require("oil").setup({
	view_options = {
		show_hidden = true,
	},
	columns = {
		"permissions",
		"size",
		"icon",
	},
	keymaps = {
		["g?"] = { "actions.show_help", mode = "n" },
		["<CR>"] = "actions.select",
		["<C-s><C-h>"] = { "actions.select", opts = { vertical = true, split = "aboveleft" } },
		["<C-s><C-j>"] = { "actions.select", opts = { horizontal = true, split = "belowright" } },
		["<C-s><C-k>"] = { "actions.select", opts = { horizontal = true, split = "aboveleft" } },
		["<C-s><C-l>"] = { "actions.select", opts = { vertical = true, split = "belowright" } },
		["<C-t>"] = { "actions.select", opts = { tab = true } },
		["<C-p><C-h>"] = { "actions.preview", opts = { vertical = true, split = "aboveleft" } },
		["<C-p><C-j>"] = { "actions.preview", opts = { horizontal = true, split = "belowright" } },
		["<C-p><C-k>"] = { "actions.preview", opts = { horizontal = true, split = "aboveleft" } },
		["<C-p><C-l>"] = { "actions.preview", opts = { vertical = true, split = "belowright" } },
		["<M-d>"] = "actions.preview_scroll_down",
		["<M-u>"] = "actions.preview_scroll_up",
		["<leader>oc"] = { "actions.close", mode = "n" },
		["<C-r>"] = "actions.refresh",
		["-"] = { "actions.parent", mode = "n" },
		["_"] = { "actions.open_cwd", mode = "n" },
		["`"] = { "actions.cd", mode = "n" },
		["~"] = { "actions.cd", opts = { scope = "tab" }, mode = "n" },
		["gs"] = { "actions.change_sort", mode = "n" },
		["gx"] = "actions.open_external",
		["g."] = { "actions.toggle_hidden", mode = "n" },
		["g\\"] = { "actions.toggle_trash", mode = "n" },
	},
	use_default_keymaps = false,
})
